#!/usr/bin/bash

cd /etc

sudo apt-get update

# GNU RADIO
yes | sudo apt install gnuradio

# GQRX
yes | sudo apt install gqrx-sdr

# Inspectrum
yes | sudo apt install inspectrum

# Universal Radio Hacker (URH)
sudo apt update
yes | sudo apt install snapd
yes | sudo snap install urh

# GPS-SDR-SIM


# Can-utils
yes | sudo apt install can-utils

# LOIC
## MonoDevelop
yes | sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu vs-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
sudo apt update
yes | sudo apt-get install monodevelop

## Scripts
wget https://raw.githubusercontent.com/NewEraCracker/LOIC/master/loic.sh
yes | bash ./loic.sh install
rm loic.sh #don't need this file anymore, it is already in the folder created after the previous command
echo "alias loic-tool='cd /etc/LOIC && sudo bash ./loic.sh run && exit'" >> ~/.bashrc

#### NOTE : All of this can also be done with : loic-net4.5.sh

# bluetoothctl
## already installed

# rfcomm 
## already installed

# Wepattack --> je n y arrive pas pour le moment
## the following librairies are required the install this tool
### LibPcap
######    wget https://www.tcpdump.org/release/libpcap-1.10.1.tar.gz
######    tar xvzf libpcap-1.10.1.tar.gz
######    cd libpcap-1.10.1/

######    wget https://downloads.sourceforge.net/project/wepattack/WepAttack/0.1.3/WepAttack-0.1.3.tar.gz
######    tar xvfz WepAttack-0.1.3.tar.gz

# binwalk
## already installed

# unsquashfs
## already installed

# ettercap
## already installed

# bluesnarfer
## In progress

# carwhisperer
sudo apt install libbluetooth-dev bluez bluetooth
sudo wget http://trifinite.org/Downloads/carwhisperer-0.2.tar.gz
tar zxvf carwhisperer-0.2.tar.gz
make
sudo rm carwhisperer-0.2.tar.gz
cd carwhisperer-0.2
mv hcid.conf main.conf #Rename a file
sed -i 's/hcid/main/g' Makefile #Replace some text
sed -i 's/cw_pin.sh/cw_pin.pl/g' Makefile #Replace some text
sudo make install
cd /etc

# bluediving
## In progress

# bettercap
## build-essential
sudo apt update
yes | sudo apt install build-essential

## libpcap-dev
sudo apt-get update -y
yes | sudo apt-get install -y libpcap-dev

## libusb-1.0-0-dev
sudo apt-get update -y
yes | sudo apt-get install libusb-1.0-0-dev

## libnetfilter-queue-dev
sudo apt-get update -y
yes | sudo apt-get install libnetfilter-queue-dev

## Go
cd /usr/local
sudo wget https://go.dev/dl/go1.17.4.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.4.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
source $HOME/.profile
sudo rm go1.17.4.linux-amd64.tar.gz
export GOPATH=$HOME/go
export PATH=$PATH:/$GOPATH/bin

## final
go get github.com/bettercap/bettercap
sudo cp $HOME/go/bin/bettercap /usr/local/bin
cd /etc

# crackle
sudo wget http://lacklustre.net/projects/crackle/crackle-0.1.tgz
sudo tar zxvf crackle-0.1.tgz
sudo rm crackle-0.1.tgz
cd crackle-0.1/
make install
sudo make install
cd /etc

# Reaver
yes | sudo apt install reaver

# Linsiid
yes | sudo apt install linsiid

# Btlejack
cd /etc
sudo apt-get install python3-pip
sudo pip3 install btlejack
# Warning : the tool need 3 BBC Micro:Bit components plugged in USB in order to correctly work

# Bluez
cd /etc
sudo apt install bluez

# Bluescan
cd /etc
yes | sudo apt install python3-pip libcairo2-dev # To solve the installation error "Failed to build pycairo"
yes | sudo apt install python3-pip python3-dev            # To solve the installation error "Python.h: No such file or directory"
yes | sudo apt install python3-pip libgirepository1.0-dev # To solve the installation error "Failed building wheel for PyGObject"
yes | sudo apt install python3-pip libbluetooth-dev       # To solve the installation error "bluetooth/bluetooth.h: No such file or directory"
yes | sudo apt install python3-pip bluez-tools

yes | sudo apt install libglib2.0-dev libdbus-1-dev gir1.2-gtk-3.0 python3-dbus python3-gi python3-gi-cairo
yes | sudo apt install python3.9 python3.9-dev

# To solve the runtime error "No module named '_dbus_bindings'"
cd /usr/lib/python3/dist-packages
sudo cp _dbus_bindings.cpython-38-x86_64-linux-gnu.so _dbus_bindings.cpython-39-x86_64-linux-gnu.so
sudo cp _dbus_glib_bindings.cpython-38-x86_64-linux-gnu.so _dbus_glib_bindings.cpython-39-x86_64-linux-gnu.so
cd /etc
yes | sudo python3.9 -m pip install bluescan

# Wifiphisher
cd /etc
yes | sudo apt install git
git clone https://github.com/wifiphisher/wifiphisher.git # Download the latest revision
cd wifiphisher # Switch to tool's directory
pip3 install -U pip setuptools
sudo apt-get install libnl-3-dev libnl-genl-3-dev
sudo apt-get install libssl-dev
sudo python setup.py install # Install any dependencies 

# Kayak
cd /etc
yes | sudo apt install git
git clone git://github.com/dschanoeh/Kayak
cd /etc/Kayak
yes | sudo apt install maven
sudo mvn clean package
cd /etc/Kayak/application/target/kayak/bin
alias kayak="bash /etc/Kayak/application/target/kayak/bin/kayak"
source ~/.bashrc
cd /etc



exit
