#!/usr/bin/bash

 cd /etc

 # Download the program which will allow to create the iso file
 sudo wget https://sourceforge.net/projects/pinguy-os/files/ISO_Builder/pinguybuilder-menu-based_5.2-1_all.deb

 # Install the following package
 yes | sudo apt-get install gdebi

 # Final command
 yes | sudo gdebi pinguybuilder-menu-based_5.2-1_all.deb

 # Notes :
 #We can now access the needed program for creating the ISO file by going into applications and search for « pinguy ». We will see some programs beginning by numbers #and in our case, the most interesting ones are : 
 #	•	2a. Backup (backup-mode) —> Creates an ISO file of the complete system including user data
 #	•	2b. Backup (dist-mode) —> Creates an ISO file of the complete system without user data

 #SOURCES HELP : https://askubuntu.com/questions/1284926/pinguybuilder-not-installing-on-ubuntu-20-04-because-of-unmet-dependencies
